name: Release

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}
  BLUECATS_HUB_VERSION: v0.5.0

jobs:
  build:
    runs-on: windows-latest
    steps:
    - id: get_version
      uses: seungyongshim/get-version-action@v1.3
    - uses: actions/checkout@v2
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.0   
    - name: release 폴더 생성
      run: |
        mkdir release
    - name: 버전 추가
      run: |
        get-childitem ./extra -recurse -include *.yml | ForEach-Object {(get-content -encoding utf8 $_.FullName) -replace 'VERSION_INFO_HERE', $env:GITHUB_VERSION | out-file -encoding utf8 $_.FullName}  
      env:
        GITHUB_VERSION: ${{ steps.get_version.outputs.version }}
    - name: Build MSI
      run: |
        env
        ./build build --cid $env:BLUECATS_HUB_VERSION --bitness x64 collectbeat
      env:
        GITHUB_VERSION: ${{ steps.get_version.outputs.version }}
    - name: copy MSI
      run: |
        Copy-Item "./bin/out/*/*"  -Destination "./release" -Filter *.msi -Recurse 
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./release/collectbeat.msi
        asset_name: collectbeat.msi
        asset_content_type: application/octet-stream
