name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_VERSION: 0.0.0
  BLUECATS_HUB_VERSION: v0.5.5

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: release 폴더 생성
      run: |
        mkdir release
    - name: 버전 추가
      run: |
        get-childitem ./extra -recurse -include *.yml | ForEach-Object {(get-content -encoding utf8 $_.FullName) -replace 'VERSION_INFO_HERE', $env:GITHUB_VERSION | out-file -encoding utf8 $_.FullName}
    - name: Build MSI
      run: |
        env
        ./build build --cid $env:BLUECATS_HUB_VERSION --bitness x64 hub
    - name: copy MSI
      run: |
        Copy-Item "./bin/out/*/*"  -Destination "./release" -Filter *.msi -Recurse 
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: beats
        path: ./release
